# generate ansible inventory with instance ips and users
resource "local_file" "ansible_inventory" {
  filename = "${path.root}/../ansible/inventories/hosts.ini"

  content = <<-EOT
# auto-generated by terraform

[master]
%{ for inst in module.ec2.instances ~}
%{ if inst.role == "master" ~}
${inst.name} ansible_host=${inst.public_ip} ansible_user=${inst.username}
%{ endif ~}
%{ endfor ~}

[workers]
%{ for inst in module.ec2.instances ~}
%{ if inst.role == "worker" ~}
${inst.name} ansible_host=${inst.public_ip} ansible_user=${inst.username}
%{ endif ~}
%{ endfor ~}

[all:vars]
ansible_ssh_private_key_file={{ inventory_dir }}/../../terraform/multiserver
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
EOT
}
